### ISSUE TITLE
Doesn't open an url that can only be accessed from a vpn

### ISSUE THREAD

**Issue by evgeniykozyrev** [roskomsvoboda/censortracker#114]
When the extension is enabled and I try to get access to resource that is only accessible via vpn (an internal resource of the company I work for), I get connection refused.
Relevant for the enabled property " Allow this extension to read and change all your data on websites that you visit".
Vpn app is a software, not extension.

**Comment by lk-geimfari** [comment]
@evgeniykozyrev Hi! Can you, please, try to check if this behaviour reproduces on using the latest version from the `develop` branch?

**Comment by lk-geimfari** [comment]
There is an archive with the latest version, if don't want to build it yourself.

[censortracker-chrome-ext.v2.0.5+1015-dev.zip](https://github.com/roskomsvoboda/censortracker/files/5207560/censortracker-chrome-ext.v2.0.5%2B1015-dev.zip)

**Comment by evgeniykozyrev** [comment]
Yes,  it looks fine now on version 2.0.5.1015

**Comment by lk-geimfari** [comment]
@evgeniykozyrev О, это хорошо.
