### ISSUE TITLE
Add the ability to disable the opening of sites through a proxy

### ISSUE THREAD

**Issue by KovalevArtem** [roskomsvoboda/censortracker#115]
![image](https://user-images.githubusercontent.com/36500228/92281907-459ccb80-ef05-11ea-9a15-bfe6dac8c50d.png)
I want to use the extension for informational purposes only.
I am using VPN to bypass blocking. And I want to be able to disable the use of proxies.

**Comment by Piterden** [comment]
Why don't you just disable extension?

**Comment by KovalevArtem** [comment]
> use the extension for informational purposes only

**Comment by lk-geimfari** [comment]
So, proxying can be disabled now. I'm closing this.
