### ISSUE TITLE
Improved color coding of extension icon

### ISSUE THREAD

**Issue by KovalevArtem** [roskomsvoboda/censortracker#116]
![Аннотация 2020-09-04 233228](https://user-images.githubusercontent.com/36500228/92283163-fa37ec80-ef07-11ea-9fb3-f660c417a402.png)
![Аннотация 2020-09-04 233248](https://user-images.githubusercontent.com/36500228/92283166-fb691980-ef07-11ea-882d-3559102fdb55.png)
Looking at the icon, I want to determine which category the site belongs to.
Now, in order to understand this, you need to click on the icon and read the information - which is not convenient ...

**Comment by KovalevArtem** [comment]
I also think it would be helpful to have the icon show the user if the site was opened through a proxy or not.
For example, put on glasses on a quokka.
(It was nicely and clearly implemented, for example, friGate)

**Comment by KovalevArtem** [comment]
Perhaps, if the site is included in the register of information dissemination organizers, use red.
If the site is banned in Russia - yellow.

**Comment by lk-geimfari** [comment]
Fixed!
