### ISSUE TITLE
Почему расширение каждые 3 минуты пытается соединиться с вашим прокси даже при выключенном Censor Tracker?

### ISSUE THREAD

**Issue by ademaro** [roskomsvoboda/censortracker#130]

**Comment by lk-geimfari** [comment]
CensorTracker makes requests to the proxy server every 3 minutes to make the proxy server allow proxying.

**Comment by msva** [comment]
@ademaro конечно, сам факт этого поведения может быть немного раздражающим, но в реальности на это уходит всего пара байт (просто TCP SYN запрос).
Это нужно для того, чтобы постучать на наш прокси-сервер, чтобы "открыть" для пользователя (его IP, точнее) порт прокси.

Иначе, если оставить порт всегда открытым для всех, в течение 5-10 минут прокси "захватывают" "китайцы" (прокси обнаруживается всеразличными сканерами, попадает в списки публичных прокси и через него начинает ходить половина китая, и ещё целая толпа людей). Что очень плохо сказывается на пропуской способности (а так же, из-за этого прилетают угрозы хостеру).

Альтернативой стуку "по времени" - было бы "стучать перед каждым запросом и делать паузу в 100-200мс".
Но, согласно @lk-geimfari, API браузеров в этом случае не позволяет удобно и без геморроя определить, будет ли проксироваться текущий запрос или нет (чтобы "стучать" только если надо проксировать)...

**Comment by ademaro** [comment]
@msva, благодарю за развёрнутый ответ!
