### ISSUE TITLE
Add English support.

### ISSUE THREAD

**Issue by toprak** [roskomsvoboda/censortracker#294]
Hi, I have just tried your extension and it works on Turkey too so can we have english translation of it.

**Comment by lk-geimfari** [comment]
> Hi, I have just tried your extension and it works on Turkey too so can we have english translation of it.

Hi! We are planning to make CensorTracker suitable for all countries with censorship. We'll definitely add English (maybe even Turkish).

**Comment by lk-geimfari** [comment]
I've added English locale
