### ISSUE TITLE
Don't use per-command environment variables to build

### ISSUE THREAD

**Issue by rakleed** [roskomsvoboda/censortracker#353]
Can you not use [per-command environment variables to build](https://github.com/roskomsvoboda/censortracker#installation)? Since it is not convenient to set up, and other projects do not use it.

**Comment by lk-geimfari** [comment]
It's not our priority task. If you have a better way to solve the problems that per-command envs solve then you can create PR.

**Comment by rakleed** [comment]
@lk-geimfari it looks like a `.env` file can be used for the same purpose, as is done, for example, in https://github.com/AdguardTeam/AdGuardVPNExtension. Can you add it and also update the build information?

**Comment by rakleed** [comment]
@lk-geimfari did you do something? Because in the README under [Installation](https://github.com/roskomsvoboda/censortracker#installation) you still recommend adding environment variables in case of problems.
