### ISSUE TITLE
vk.com no images/ no audio / etc

### ISSUE THREAD

**Issue by veksha** [roskomsvoboda/censortracker#362]
![image](https://user-images.githubusercontent.com/275333/162460264-9d11f5e2-4b6b-451e-8fd4-46c2b845f44e.png)

**Comment by Erghel** [comment]
Я правильно понимаю, что у вас без расширения ВК не открывается?

**Comment by veksha** [comment]
> Я правильно понимаю, что у вас без расширения ВК не открывается?

без расширения - заблокировано (естественно)
с вот этим расширением работает исправно --> [chrome extension link](https://chrome.google.com/webstore/detail/%D1%80%D0%B0%D0%B7%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%B2%D0%BA-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5/ahdigjdpekdcpbajihncondbplelbcmo/)

так что делаю вывод, что проблема не в браузере (brave) и не в настройках ОС.

**Comment by Erghel** [comment]
Расширение CensorTracker не очень сочетается с другими расширениями, которые могут проксировать что-либо. 

Поэтому, чтобы решить проблему с CT выключите в настройках другие расширения, которые что-то проксируют

**Comment by lk-geimfari** [comment]
@veksha We have a database of blocked sites in Ukraine, but we don't know exactly how well the extension works in Ukraine. You can try to add the necessary sites to the list for proxying yourself.

**Comment by lk-geimfari** [comment]
Here is a `JSON` file of websites that we're proxying for Ukrainian users: https://registry.censortracker.org/api/v4/domains/ua/json/

**Comment by veksha** [comment]
> Here is a `JSON` file of websites that we're proxying for Ukrainian users: https://registry.censortracker.org/api/v4/domains/ua/json/

![image](https://user-images.githubusercontent.com/275333/162474035-98ae9c37-321c-41b5-84d0-89f8089171c2.png)

vk.com uses userapi.com for images/etc..
maybe you should add it too for Ukraine?
