### ISSUE TITLE
By analogy with the antizapret

### ISSUE THREAD

**Issue by SOYAllure** [roskomsvoboda/censortracker#390]
Пожалуйста, реализуйте работу функционала по существу на примере, как это реализовано в Антизапрете. Возможно есть какой-то более изящный вариант. Но подразумевается, что работать будет так:
есть конфигурационный файл *.ovpn
этот файл помещаем в приложение openvpn
включаем работу по файлу в openvpn
радоваемся, что родители привыкшие к интернету в телефоне - не могут получить доступ к вредным сайтам.

(на странице antizapret есть ссылка на ваш ресурс.скорее всего вы заодно и скоро всё будет работать не только для десктопов)

**Comment by lk-geimfari** [comment]
The feature is out of CensorTracker's scope, so we can't do this.

**Comment by 0xb1b1** [comment]
This feature is not possible to implement in a browser extension without falling back to a background service to reliably enforce redirects. In case of the "parental" control feature, it would require a root CA to intercept in- and outbound traffic, - and it's a security threat. @lk-geimfari please plose this issue.

P. S.: you could utilize the hosts file on your local machine to achieve this effect. Also, PiHole is a viable option.
