### ISSUE TITLE
The current version overloads the processor

### ISSUE THREAD

**Issue by zloirock** [roskomsvoboda/censortracker#392]
![telegram-cloud-photo-size-2-5242729732435460788-y](https://user-images.githubusercontent.com/2213682/171591455-55ec45ca-dfa9-4be0-b893-9446c3132700.jpg)

That causes constant active cooling on M1.

M1, macOS 12.4, Chrome 102.0.5005.61

Different websites (~30 tabs).

There are no other extensions responsible for proxying.

**Comment by zloirock** [comment]
Some times for the second, the service worker logs those messages:
```js
Console: {"lineNumber":1,"message":"Found IDO data for avito.ru","message_level":2,"sourceIdentifier":3,"sourceURL":"chrome-extension://gaidoampbkcknofoejhnhbhbhhifgdop/background.js"}
Console: {"lineNumber":1,"message":"Settings.setDangerIcon()","message_level":1,"sourceIdentifier":3,"sourceURL":"chrome-extension://gaidoampbkcknofoejhnhbhbhhifgdop/background.js"}
Console: {"lineNumber":1,"message":"Found IDO data for avito.ru","message_level":2,"sourceIdentifier":3,"sourceURL":"chrome-extension://gaidoampbkcknofoejhnhbhbhhifgdop/background.js"}
Console: {"lineNumber":1,"message":"Settings.setDangerIcon()","message_level":1,"sourceIdentifier":3,"sourceURL":"chrome-extension://gaidoampbkcknofoejhnhbhbhhifgdop/background.js"}

```

**Comment by zloirock** [comment]
![telegram-cloud-photo-size-2-5242729732435460881-y](https://user-images.githubusercontent.com/2213682/171611586-daa93a96-02e3-4f45-b527-dbd3e3377379.jpg)
![telegram-cloud-photo-size-2-5242729732435460897-y](https://user-images.githubusercontent.com/2213682/171611610-bffa8f2f-cb5d-4e43-99e2-c802e5c86043.jpg)

**Comment by zloirock** [comment]
Still the same:

![image](https://user-images.githubusercontent.com/2213682/176199382-ce34b2c2-1062-4c01-b0b2-4acd0ce53c9a.png)

It looks like one of the problem websites is Avito.

**Comment by lk-geimfari** [comment]
Fixed.
