### ISSUE TITLE
Inconsistent naming scheme

### ISSUE THREAD

**Issue by 0xb1b1** [roskomsvoboda/censortracker#398]
In some strings, the extension's name appears to be CensorTracker; in others, however, it's Censor Tracker. It's unclear which one should be considered the project's official name.

**Comment by lk-geimfari** [comment]
That's true. It's `CensorTracker`, not `Censor Tracker`.

**Comment by Erghel** [comment]
@0xb1b1 I will fix it.

**Comment by 0xb1b1** [comment]
> That's true. It's `CensorTracker`, not `Censor Tracker`.

@lk-geimfari it seems like the add-on in published on `Firefox Browser Add-ons` featuring `Censor Tracker` as its title.

**Comment by lk-geimfari** [comment]
Fixed by @Erghel in #399

**Comment by 0xb1b1** [comment]
Fixed by the following commits:
- 4364002f83712e56cd5f48bc39d1bcae846a6b60
- 231c8531aa0a18c085a537ffd6846c017cc0dbe7
- d3e419a042427c3ef42278d6907851ac18549601
- 5774872cd6bccf45bb02090c4ff84cef89455acc
