### ISSUE TITLE
Add emergency mode

### ISSUE THREAD

**Issue by lk-geimfari** [roskomsvoboda/censortracker#400]
To make `Censor Tracker` work even in conditions of complete blocking of all our IP addresses and hosts.

Configs must be stored on following Hosts/CDN's:
1. Github
2. Netlify
3. Bitbucket
4. Cloudflare

**Comment by lk-geimfari** [comment]
Also, we can use github pages: https://roskomsvoboda.github.io/censortracker-configs/emergency-endpoints.json

**Comment by Erghel** [comment]
Maybe Replit can help too?

**Comment by lk-geimfari** [comment]
I think that Netlify and Github Pages will be enough.
