### ISSUE TITLE
Chromium 86.0.4240.198

### ISSUE THREAD

**Issue by MaximusPanin** [roskomsvoboda/censortracker#421]
Hello.
Is there anything I can do to make the app work on the old Chromium 86.0.4240.198 ?

![Снимок экрана 2022-06-23 171700](https://user-images.githubusercontent.com/24373505/175334301-4983c21f-1333-422c-b111-2a10f3737ce0.jpg)

**Comment by Erghel** [comment]
> Hello. Is there anything I can do to make the app work on the old Chromium 86.0.4240.198 ?
> 
> ![Снимок экрана 2022-06-23 171700](https://user-images.githubusercontent.com/24373505/175334301-4983c21f-1333-422c-b111-2a10f3737ce0.jpg)

The extension works with version 98 or higher of the browser. 
Update your browser.
