### ISSUE TITLE
Can't build extension: `node: --openssl-legacy-provider is not allowed in NODE_OPTIONS`

### ISSUE THREAD

**Issue by rakleed** [roskomsvoboda/censortracker#435]
I can't build the extension on macOS 12.4, since I get `node: --openssl-legacy-provider is not allowed in NODE_OPTIONS` error.

I tried with node 18.6.0 and 16.16.0. Adding environment variables doesn't help either.

Remove `NODE_OPTIONS=--openssl-legacy-provider` from https://github.com/roskomsvoboda/censortracker/blob/088eb8fe6d0340d7f410513a9f9220fdf3a864d8/package.json#L9 seems to resolve the problem.

**Comment by lk-geimfari** [comment]
We have to fix this, @adam-kad.
