### ISSUE TITLE
Add button/menu item - Add the current domain/site to "My list of proxied sites"

### ISSUE THREAD

**Issue by Inkobob** [roskomsvoboda/censortracker#445]
Ситуация: открываю/перехожу на сайт, а он заблокирован.
Текущие действия: нужно скопировать домен, открыть настройки дополнения и вручную прописать в списке проксируемых сайтов этот домен
Пожелание: добавьте возможность быстро добавлять текущий не открывающийся сайт в "Мой список проксируемых сайтов"

**Comment by Erghel** [comment]
Внесение таким образом может некорректно отрабатывать во многих ситуациях (ИМХО), пример: 
Есть ресурс, который нельзя открыть - ``play.google.com``, допустим, что нажав на кнопку он добавился в список, но вот незадача, прокси не отработает на нем, так как для корректной работы нужно внести просто ``google.com`` и так со многими сайтами, в которых нужно убрать либо ``www``, либо еще что-то для корректной отработки. 

Также, я сомневаюсь, что это будет корректно отрабатывать, если пользователь зайдет на заблокированный ресурс вида``example.com/123tehrserwehrdh65ydry`` тем самым внеся домен некорректно.

Финальный ответ в любом случае за разработчиками.

**Comment by Inkobob** [comment]
Да, это понятно, я ж так и написал - _"вручную прописать в списке проксируемых сайтов **этот домен**"_
Естественно, поддомены не учитываются.

**Comment by lk-geimfari** [comment]
Добавлено в версии 9.0.0
