### ISSUE TITLE
katfile.com проблема с загрузкой файлов

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#446]
Сайт **``katfile.com``** находится в реестре и спокойно проксируется, то есть доступ к нему есть. Но вот его поддомен **``http://s955.katfile.com:183``** открыть не удается, соотвественно загрузить контент также не представляется возможным.

**Comment by TheAirBlow** [comment]
Вот [эта функция](https://github.com/roskomsvoboda/censortracker/blob/80582bc4b5d3913225408dbe0cc8d6db838f0619/src/shared/js/background/registry.js#L193) достаёт `hostname` из URL (`s955.katfile.com`), но этот домен **не** находится в реестре и соответсвенно, **не должен** блокироваться. Разширение работает как оно и должно. 

Походу коробочка РосКомПозора у твоего ISP блокирует и сабдомены, т.к. в моём случае этот сайт с этого сабдомена у меня открывается. Добавь этот домен в Proxying List чтобы разширение пропускало и этот сабдомен через прокси. Сначала попробуй `*.katfile.com`, если не сработает то придётся все сабдомены прописывать вручную.

Предлагаю добавть галОчку которая заставит разширение проверять только SLD домен на наличие блокировок, а не домен вместе с сабдоменами.

**Comment by Erghel** [comment]
В том и дело, что расширение не работает с сабдоменами, и чтобы условно запроксировать ``play.google.com`` нужно внести в Proxying List - ``google.com``, тогда на ``play.google.com`` возможно будет получить доступ, также проблема с доступом у указанному домену (``s955.katfile.com``) обусловлена тем, что он имеет незащищенный протокол ``http``.

**Comment by TheAirBlow** [comment]
> В том и дело, что расширение не работает с сабдоменами, и чтобы условно запроксировать `play.google.com` нужно внести в Proxying List - `google.com`, тогда на `play.google.com` возможно будет получить доступ

Щас решил чекнуть PAC скрипт, разширение убирает сабдомен - [тык суда](https://github.com/roskomsvoboda/censortracker/blob/fb1f1d93b2bb05ba7652d0844d3ba20003d6af63/src/shared/js/background/proxy.js#L161). Проверил - код работает.

> также проблема с доступом к указанному домену (`s955.katfile.com`) может быть обусловлена тем, что он имеет незащищенный протокол `http`.

Нет. Например, `https://test.twitter.com/` не определяется заблокированным сайтом, но вот `https://twitter.com` проксируется.

**Comment by TheAirBlow** [comment]
@Erghel похоже что оно на самом деле проксирует сайт, но вот в UI этого он не отображает т.к. использует `hostname`.
Попытался зайти без разширения - "400 Bad Request", зашел с ним - `{"err": "access denied"}`

**Comment by Erghel** [comment]
Не совсем вас понял. 

Касательно того, что вы написали выше - `twitter` находится в реестре и блокируется по маске ([Реестр Роскомсвободы](https://reestr.rublacklist.net/ru/record/4106096/)), соответственно всего его сабдомены тоже подлежат блокировке. 

`katfile` заблокирован, но не по маске, а сугубо домен `katfile.com` и `www.katfile.com`, прокси запрос отрабатывает нормально, о чем говорил один разработчик из команды Censor Tracker в чате, в котором обсуждают работу Censor Tracker, но все равно прокси отдает 400, так как имеет `http`, а не `https`.
