### ISSUE TITLE
Показ уведомлений самопроизвольно включается

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#447]
> периодически сбрасывается во включенное состояние галка "показывать системные уведомления"

В браузере **Firefox Developer Edition** и, возможно, других, если выключить показ системных уведомлений, то они могут самопроизвольно включиться вновь.

**Comment by TheAirBlow** [comment]
Все настройки разширение подтягивает из `Browser.storage.local`, который в коде НИКОГДА не сбрасывается. Поиск `storage.clear` ничего не выдаёт (данная функция существует), а также галОчка переключается только когда юзер это сделал сам: [тык суда](https://github.com/roskomsvoboda/censortracker/search?q=storage.set%28%7B+showNotifications%3A)

**Comment by Erghel** [comment]
Но жалобы поступают и данную проблему нужно было зафиксировать для дальнейшего фикса. Если судить по описанию одного из пользователей, у которого стоит сборка **Firefox Developer Edition**, то проблема может быть именно в самой этой сборке, которая к тому же часто обновляется, что может провоцировать сброс.

**Comment by lk-geimfari** [comment]
I'm closing this since I can't reproduce it. Feel free to reopen it with more details about how to reproduce this behavior.

**Comment by Kyogre** [comment]
возможно дубль https://github.com/censortracker/censortracker/issues/657
