### ISSUE TITLE
Не работает функция проксирования "вашего листа" в разделе Регион

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#452]
![изображение](https://user-images.githubusercontent.com/88831850/190215936-d3ac7989-8d54-449d-a765-36bbb97ec0f5.png)

При выборе этой функции у пользователя продолжают открываться сайты из реестра заблокированных.

**Comment by lk-geimfari** [comment]
I've fixed this one.

**Comment by Erghel** [comment]
This [commit](https://github.com/roskomsvoboda/censortracker/commit/5644393ce7fd4fa1d06082d1a73241c08365d2c7) fix it.
