### ISSUE TITLE
Не получается включить расширение.

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [roskomsvoboda/censortracker#455]
При попытке включить расширение в chrome://extensions/ , то переключатель становится синим и сразу пропадает. Такое же происходит, если загрузить расширение, как распакованное
![image](https://user-images.githubusercontent.com/98014624/192100760-5180bc6b-15c9-4494-aa40-f14b79068c4b.png)

**Comment by Erghel** [comment]
Здравствуйте!
А у вас есть сторонние расширения для обхода блокировок?

**Comment by MIPOHBOPOHIH** [comment]
> Здравствуйте! А у вас есть сторонние расширения для обхода блокировок?

да, оказывается одно расширение мешало

**Comment by Erghel** [comment]
> > Здравствуйте! А у вас есть сторонние расширения для обхода блокировок?
> 
> да, оказывается одно расширение мешало

Тогда, если все решилось, закройте пожалуйста этот issue!
