### ISSUE TITLE
Домены youtube возвращаются в Игнорирумые после перезагрузки

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#462]
Если попробовать убрать домены `youtube.com` и `youtu.be` из списка Игнорируемых в расширении, а после перезагрузить браузер, то эти домены вновь окажутся там (см. фото).

При этом, внося другие домены и удаляя их - проблема не возникает. 
![изображение](https://user-images.githubusercontent.com/88831850/193470143-06244f89-150d-43ea-9fac-8d64087fa2cf.png)
![изображение](https://user-images.githubusercontent.com/88831850/193470155-5a22a976-f748-40d6-b527-54f155373928.png)![изображение](https://user-images.githubusercontent.com/88831850/193470143-06244f89-150d-43ea-9fac-8d64087fa2cf.png)

**Comment by lk-geimfari** [comment]
We have decided to exclude IT from ignoring.
