### ISSUE TITLE
Кнопка добавления в "мой список проксируемых сайтов"

### ISSUE THREAD

**Issue by grogloog** [roskomsvoboda/censortracker#463]
Хотелось бы видеть в окне расширения кнопку добавления url текущей вкладки в "мой список проксируемых сайтов"

**Comment by Erghel** [comment]
Issue с данной просьбой уже открыт и разработчики приняли его во внимание для реализации в будущих версиях расширения. 

https://github.com/roskomsvoboda/censortracker/issues/445
