### ISSUE TITLE
Proxying list subdomains

### ISSUE THREAD

**Issue by ringoz** [roskomsvoboda/censortracker#579]
Why can't I add "play.google.com" to proxying list?
It always converts the entry to "google.com", which I do not want to be proxied.

**Comment by Erghel** [comment]
Hello!

At the moment Censor Tracker does not have the ability to proxy only subdomains, instead it proxies the domain on which the subdomain is located.

**Comment by ringoz** [comment]
Okay, will you accept PR which fixes the issue?
