### ISSUE TITLE
The function updateState executed each time user click on the tab

### ISSUE THREAD

**Issue by lk-geimfari** [roskomsvoboda/censortracker#58]
For incomprehensible reasons `chrome.tabs.onUpdated` executes its listener four times.

Update:

Well, seems like this is completely normal behavior for chrome.tabs.onUpdated because it fires for iframes too.

So, we must use `webNavigation.onCompleted` instead.

**Comment by Piterden** [comment]
@lk-geimfari It should be called only when the state need to be updated. That's why I asked you to draw a block-scheme for inner logic and behavior.

**Comment by lk-geimfari** [comment]
@Piterden The state can be updated only after creating a request, so `onComplete` is fit for us. 

As you can see, it will execute only once per request:
![image](https://user-images.githubusercontent.com/15812620/87328501-3c633400-c53e-11ea-89f4-cd923f8e67a0.png)
