### ISSUE TITLE
https everywhere

### ISSUE THREAD

**Issue by dev-dsp** [roskomsvoboda/censortracker#61]
Насколько я понимаю, расширение на данный момент форсирует использование https. Возможно ли добавить исключения для некоторых адресов?

**Comment by lk-geimfari** [comment]
Боюсь, что на данный момент — нет. Принудительное перенаправление совершенно необходимо для выявления блокировок, сделанных в обход реестра запрещенных сайтов. Мы планируем добавить страницу опций и тогда такая возможность появится.

**Comment by dev-dsp** [comment]
Если это есть в планах - уже хорошо :)
Сейчас приходится использовать incognito или другой браузер для локальных сайтов и сервисов в приватных сетях (127.0.0.0/8, 172.16.0.0/12, 10.0.0.0/8, 192.168.0.0/16).

**Comment by lk-geimfari** [comment]
Их мы обязательно будем исключать. Спасибо, что напомнили!

**Comment by lk-geimfari** [comment]
I'm closing this since there is #62
