### ISSUE TITLE
Random refreshing of pages.

### ISSUE THREAD

**Issue by drewaaaaa** [roskomsvoboda/censortracker#613]
Случайно перезагружаются активные вкладки, когда расширение включено. Перезагружаются даже страницы с localhost, не говоря уже о страницах c просматриваемыми видео.

Mozilla Firefox 113.0.2 (64-разрядный), Windows 10 22h2.

Проблема "плавающая", т.к. я не могу повторить происходящее специально.

**Comment by lk-geimfari** [comment]
Fixed in 15.0.0
