### ISSUE TITLE
Please add t.co to default list of proxying sites.

### ISSUE THREAD

**Issue by drewaaaaa** [roskomsvoboda/censortracker#614]
Твиттер не открывается без расширения, не открываются и ссылки, прошедшие через их сокращатель. С расширением твиттер работает, но по ссылкам ходить не получается. Прошу добавить в список проксируемых по умолчанию сайтов t.co.

**Comment by lk-geimfari** [comment]
Добавил. В скором времени расширение само спулит домены и тогда t.co тоже будет проксироваться. Спасибо, что сообщили о проблеме.
