### ISSUE TITLE
Outdated certificates?

### ISSUE THREAD

**Issue by drewaaaaa** [roskomsvoboda/censortracker#615]
![изображение](https://github.com/roskomsvoboda/censortracker/assets/50954426/2fa81ed7-e532-470a-a78d-c9ac218cc92c)
![изображение](https://github.com/roskomsvoboda/censortracker/assets/50954426/e479bd70-caeb-4a98-9f26-c175d847b7b9)

иногда каспер блокирует подключение по этому сертификату или запрашивает подтверждение.

**Comment by msva** [comment]
1) сертификаты роскомсвободы вообще не должны там использоваться
2) есть подозрение, что дело в некорректной работе модуля антивируса, который вторгается в http(s)-трафик. :shrug:

**Comment by drewaaaaa** [comment]
В принципе с того момента не возникало более, можно закрыть issue
