### ISSUE TITLE
Сбрасывается регион после экспорта настроек

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#627]
Воспроизведение: 
1. Зайти в раздел "Регион"
2. Выбрать любую страну пребывания
3. Выключить настройку "Открывать сайты из реестра заблокированных сайтов"
4. Зайти в раздел "Продвинутые настройки" и экспортировать настройки
5. Зайти в раздел "Регион" и включить настройку "Открывать сайты из реестра заблокированных сайтов"

**Comment by lk-geimfari** [comment]
@Erghel Я не уверен, что это можно считать за баг. Страна сбрасывается не из-за экспорта, а из-за отключения реестра.

**Comment by lk-geimfari** [comment]
It's feature not a bug.
