### ISSUE TITLE
Изменить формулировку ошибки "прокси работает с перебоями"

### ISSUE THREAD

**Issue by Erghel** [roskomsvoboda/censortracker#628]

**Comment by msva** [comment]
прокси как таковые - работают (в основном) хорошо.

В 99% случаев появления этого сообщения проблема заключается в связности конкретного юзера с ними.

Так что, чтобы не дискредитировать самих же себя, имхо, лучше использовать нейтральную формулировку.

Не "прокси работает херово", а "не получается связаться с прокси-серверами" (или "нет связи с ..."), или в таком духе.
