### ISSUE TITLE
Для пк будет версия ?

### ISSUE THREAD

**Issue by Patraskon** [roskomsvoboda/censortracker#640]

**Comment by msva** [comment]
Можно поконкретнее, пожалуйста?

Чем текущие версии "не для ПК"?

**Comment by Patraskon** [comment]
Ну это для браузеров конкретно.

**Comment by msva** [comment]
Да.
CensorTracker - это расширение для браузеров.
Именно как расширение для браузеров оно и писалось.

Другое "для ПК" к нему не применимо.

Это не VPN.

Более того, ничто из "для браузеров" не VPN и физически не может им быть.
И если оно пишет обратное в названии или описании и при этом не требует дополнительной установки отдельной программы на компьютер - оно 100% врёт и не является VPN.


В общем, TL;DR:
CensorTracker это расширение, которое управляет прокси в браузере.
Оно не предназначено для общесистемного использования. Да и в этом всё равно нет смысла: проксировать всё равно возможно не весь трафик. Только TCP. Тот же UDP - никак не проксировать (а это - как минимум звонки в мессенджерах, торренты, DNS и т.п.)


Если хочется перенаправлять весь системный трафик - для этого есть AmneziaVPN.
Это наш сестринский проект.
Тоже бесплатный и с открытым кодом.
Но не смотря на его бесплатность, рекомендуемый способ установки - если вы арендуете (платно) VPS у одного из хостеров и укажете приложению реквизиты доступа на него. И оно настроит вам VPN.
А совсем бесплатный доступ к ограниченному VPN (если его ещё не прикрыли, к сожалению, не слежу) - следует считать как "пробный".
