### ISSUE TITLE
*.onion сайты

### ISSUE THREAD

**Issue by EvPix** [roskomsvoboda/censortracker#649]
Безопасно ли заходить на *.onion сайты через данное расширение(раз расширение даёт такую возможность без Tor) или лучше использовать Tor браузер для данных сайтов?

**Comment by lk-geimfari** [comment]
@EvPix Когда вы заходите на сайты из оверлейных сетей, весь трафик пускается по соответствующей оверлейной сети. Для `*.onion` — это Tor, для `*.i2p` соотвественно I2P.

Безопасность понятие сильно субъективное, потому все зависит от вашего взгляда на то, что вы считаете безопасным, а что — нет. Безопасно оставлять включенным JS? Большинство экспертов в кибербезопасности вам скажет, что это не очень безопасно и потенциально может служить причиной деанонимизации, но без JS большинство современных сайтов не будут нормально отображаться.

Вообще, если выхотите сохранить полную анонимность, то лучше использовать Tor Browser, так как в него встроены дополнительные механизмы, позволяющие сохранить больший уровень анонимности.

**Comment by lk-geimfari** [comment]
Кстати, для таких обсуждений у нас есть [чат в Telegram](https://t.me/CensorTracker_feedback).

**Comment by EvPix** [comment]
> Вообще, если выхотите сохранить полную анонимность, то лучше использовать Tor Browser, так как в него встроены дополнительные механизмы (включая и отсутствие поддержки протокола WebRTC, который всегда служит причиной утечки IP адреса), позволяющие сохранить больший уровень анонимности.

То есть через Censor Tracker трафик будет утекать правоохранительным органам в отличие от Tor для *.onion сайтов?


> Кстати, для таких обсуждений у нас есть [чат в Telegram](https://t.me/CensorTracker_feedback).

Спасибо, но я не хотел бы участвовать в таких масштабных чатах для обсуждения. Так как мой вопрос весьма мизерный. И после этого я уже не буду спрашивать от чём либо, так как больше мне нечего спросить.

**Comment by lk-geimfari** [comment]
Нет, трафик правохранительным органам утекать не будет, но использую Onion Network через расширение вы можете потенциально раскрыть свой IP, по причинам описанным выше.

**Comment by EvPix** [comment]
Спасибо за ответы и полезную информацию. Закрываю issue.
