### ISSUE TITLE
http://pornreactor.cc почему не грузит полностью?

### ISSUE THREAD

**Issue by PhoenixIndigo** [roskomsvoboda/censortracker#655]

**Comment by Erghel** [comment]
Что вы имеете в виду под "грузится не полностью"?

У вас не подгружаются картинки или другой контент? Если так, то вполне вероятно, что загрузка идет со стороннего домена, который нужно добавить в список проксируемых сайтов (в настройках расширения), подобные доп. домены можно найти в консоли браузера, зайдя на нужный вам сайт, открыв консоль и перейдя в раздел "Сеть".

**Comment by PhoenixIndigo** [comment]
Не грузятся поддомены которые не добавить отдельно от осановного ресурса. снимок выше

**Comment by Erghel** [comment]
> Не грузятся поддомены которые не добавить отдельно от основного ресурса. снимок выше

Картинки находятся на том же домене, что и сайт, просто подгружаются с поддомена? Стоит ли у вас дополнительно плагин от reactor cc? Отладочную информацию расширения есть возможность показать?

**Comment by PhoenixIndigo** [comment]
```
{
  "countryCode": "RU",
  "countryName": "Russia",
  "customRegistryUrl": "https://registry.censortracker.org/api/v3/dpi/",
  "ignoreUrl": null,
  "proxyUrl": "https://app.censortracker.org/api/proxy-config/",
  "registryUrl": "https://registry.censortracker.org/api/v3/ct-domains/",
  "specifics": {
    "cooperationRefusedORIUrl": "https://registry.censortracker.org/api/v3/disseminators/refused/"
  },
  "configEndpointUrl": "https://raw.githubusercontent.com/roskomsvoboda/ctconf/main/config.json",
  "configEndpointSource": "GitHub",
  "conflictingExtensions": [
    "Hide My IP",
    "LostFilm.TV",
    "Browsec VPN",
    "1VPN"
  ],
  "version": "18.0.0",
  "browser": {
    "name": "Firefox",
    "version": "120"
  },
  "proxyLastFetchTs": 1702852101201,
  "badProxies": [],
  "currentProxyURI": {
    "proxyServerProtocol": "HTTPS",
    "proxyServerURI": "proxy-i3.censortracker.org:59667"
  },
  "proxyControlled": true
}
```

**Comment by Erghel** [comment]
> ```
> {
>   "countryCode": "RU",
>   "countryName": "Russia",
>   "customRegistryUrl": "https://registry.censortracker.org/api/v3/dpi/",
>   "ignoreUrl": null,
>   "proxyUrl": "https://app.censortracker.org/api/proxy-config/",
>   "registryUrl": "https://registry.censortracker.org/api/v3/ct-domains/",
>   "specifics": {
>     "cooperationRefusedORIUrl": "https://registry.censortracker.org/api/v3/disseminators/refused/"
>   },
>   "configEndpointUrl": "https://raw.githubusercontent.com/roskomsvoboda/ctconf/main/config.json",
>   "configEndpointSource": "GitHub",
>   "conflictingExtensions": [
>     "Hide My IP",
>     "LostFilm.TV",
>     "Browsec VPN",
>     "1VPN"
>   ],
>   "version": "18.0.0",
>   "browser": {
>     "name": "Firefox",
>     "version": "120"
>   },
>   "proxyLastFetchTs": 1702852101201,
>   "badProxies": [],
>   "currentProxyURI": {
>     "proxyServerProtocol": "HTTPS",
>     "proxyServerURI": "proxy-i3.censortracker.org:59667"
>   },
>   "proxyControlled": true
> }
> ```

```
"conflictingExtensions": [
    "Hide My IP",
    "LostFilm.TV",
    "Browsec VPN",
    "1VPN"
  ]
```
Для начала отключите сторонние расширения в настройках браузера (about:addons), так как управлять прокси может только 1 расширение и при большом их количестве одновременно они могут конфликтовать. После отключения переустановите Censor Tracker, заранее сохранив список проксирования, чтобы его можно было потом сохранить. Произведя переустановку - проверьте работоспособность.

А вообще у pornreactorcc будет такая же проблема, как у joyreactorcc (если я правильно понимаю, что эти 2 ресурса от одних и тех же создателей), то есть поддомены не будут работать через прокси (блокируя запросы или еще что-то).

**Comment by PhoenixIndigo** [comment]
Расширения были в пассивных режимах, непонятно почему их надо отключать, а расширения которые с другими несовместимы неустанавливаю! По вашей рекомендации всё также. Кем заблочены поддомены, если не с первого раза но грузятся расширением от https://antizapret.prostovpn.org , но там недоступны ссылки непонятно отчего.

**Comment by Erghel** [comment]
> Расширения были в пассивных режимах, непонятно почему их надо отключать, а расширения которые с другими несовместимы неустанавливаю! По вашей рекомендации всё также. Кем заблочены поддомены, если не с первого раза но грузятся расширением от https://antizapret.prostovpn.org , но там недоступны переходы по ссылкам непонятно отчего.

Если бы они были корректно отключены - они бы не отображались в отладочной информации. Отключение через окошко расширения не дает никаких гарантий того, что расширение не будет работать на фоне.  Отключать их нужно, чтобы они не мешали расширению использовать настройки прокси. которые напомню - может использовать только одно расширение. 

Что касается недоступности, то сам ресурс может блокировать запросы через прокси на его поддомены и причин этому может быть масса. Для лучшего понимания хотелось бы увидеть скриншот ошибки из консоли браузера (раздел "Сеть"), где будет понятно с какой ошибкой прокси не могут получить доступ к поддомену(-ам), а также покажите повторно отладочную информацию.

**Comment by PhoenixIndigo** [comment]
После переустановки не открывает пока не перезапустить после приостановки!
<details><summary>Code</summary>
<p>

```
{
  "countryCode": "RU",
  "countryName": "Russia",
  "customRegistryUrl": "https://registry.censortracker.org/api/v3/dpi/",
  "ignoreUrl": null,
  "proxyUrl": "https://app.censortracker.org/api/proxy-config/",
  "registryUrl": "https://registry.censortracker.org/api/v3/ct-domains/",
  "specifics": {
    "cooperationRefusedORIUrl": "https://registry.censortracker.org/api/v3/disseminators/refused/"
  },
  "configEndpointUrl": "https://raw.githubusercontent.com/roskomsvoboda/ctconf/main/config.json",
  "configEndpointSource": "GitHub",
  "conflictingExtensions": [],
  "version": "18.0.0",
  "browser": {
    "name": "Firefox",
    "version": "120"
  },
  "proxyLastFetchTs": 1702981268737,
  "badProxies": [],
  "currentProxyURI": {
    "proxyServerProtocol": "HTTPS",
    "proxyServerURI": "proxy-i3.censortracker.org:59667"
  },
  "proxyControlled": true
}
``` 

</p>
</details> 

<details><summary>Shot</summary>
<p>

![](https://github.com/roskomsvoboda/censortracker/assets/107413021/8be7af0b-189d-4ab4-8823-699aaaf88036)

</p>
</details>

**Comment by PhoenixIndigo** [comment]
При этом содержимое https://img2.pornreactor.cc открываетя в https://img0.pornreactor.cc как с прокси так и без!
