### ISSUE TITLE
https://adguard.com/ не открывает

### ISSUE THREAD

**Issue by PhoenixIndigo** [roskomsvoboda/censortracker#656]
добавил у себя в расширение в Файрфоксе и этот гемор повторять в Хроме, Эдже и на ноуте?

**Comment by Erghel** [comment]
С какой ошибкой не открывается ресурс? О каком "геморе" идет речь? Что отображается в отладочной информации?

**Comment by msva** [comment]
> этот гемор повторять в Хроме, Эдже и на ноуте?

1) "гемор" - это "нажать на иконку расширения, в открывшемся меню на "точки" возле имени домена и в дополнительном раскрывшемся куске нажать на "всегда""? Правда? Три клика - это гемор? :man_facepalming: 

2) а "не гемор" по-вашему было бы как? чтобы каждый сайт добавленный каждым юзером деплоился на всех и в итоге список доменов весил бы по 200 гигабайтов и расширение полгода тормозило бы при открытии каждого сайта ища в этом списке домен открываемого сайта?

// на самом деле, решением могло бы стать введение возможности создавать свои аккаунты на бекенде расширения и добавление возможности авторизовываться в них, но разработчики вряд ли смогут заняться этим в ближайшее время :man_shrugging:

**Comment by PhoenixIndigo** [comment]
Гемор ввести домен в каждом расширении на каждом компе

**Comment by PhoenixIndigo** [comment]
```
{
  "countryCode": "RU",
  "countryName": "Russia",
  "customRegistryUrl": "https://registry.censortracker.org/api/v3/dpi/",
  "ignoreUrl": null,
  "proxyUrl": "https://app.censortracker.org/api/proxy-config/",
  "registryUrl": "https://registry.censortracker.org/api/v3/ct-domains/",
  "specifics": {
    "cooperationRefusedORIUrl": "https://registry.censortracker.org/api/v3/disseminators/refused/"
  },
  "configEndpointUrl": "https://raw.githubusercontent.com/roskomsvoboda/ctconf/main/config.json",
  "configEndpointSource": "GitHub",
  "conflictingExtensions": [
    "Hide My IP",
    "LostFilm.TV",
    "Browsec VPN",
    "1VPN"
  ],
  "version": "18.0.0",
  "browser": {
    "name": "Firefox",
    "version": "120"
  },
  "proxyLastFetchTs": 1702852101201,
  "badProxies": [],
  "currentProxyURI": {
    "proxyServerProtocol": "HTTPS",
    "proxyServerURI": "proxy-i3.censortracker.org:59667"
  },
  "proxyControlled": true
}
```

**Comment by PhoenixIndigo** [comment]
![](https://github.com/roskomsvoboda/censortracker/assets/107413021/df391639-1df1-4098-8c10-97170d6a2e43)

**Comment by Erghel** [comment]
> ```
> {
>   "countryCode": "RU",
>   "countryName": "Russia",
>   "customRegistryUrl": "https://registry.censortracker.org/api/v3/dpi/",
>   "ignoreUrl": null,
>   "proxyUrl": "https://app.censortracker.org/api/proxy-config/",
>   "registryUrl": "https://registry.censortracker.org/api/v3/ct-domains/",
>   "specifics": {
>     "cooperationRefusedORIUrl": "https://registry.censortracker.org/api/v3/disseminators/refused/"
>   },
>   "configEndpointUrl": "https://raw.githubusercontent.com/roskomsvoboda/ctconf/main/config.json",
>   "configEndpointSource": "GitHub",
>   "conflictingExtensions": [
>     "Hide My IP",
>     "LostFilm.TV",
>     "Browsec VPN",
>     "1VPN"
>   ],
>   "version": "18.0.0",
>   "browser": {
>     "name": "Firefox",
>     "version": "120"
>   },
>   "proxyLastFetchTs": 1702852101201,
>   "badProxies": [],
>   "currentProxyURI": {
>     "proxyServerProtocol": "HTTPS",
>     "proxyServerURI": "proxy-i3.censortracker.org:59667"
>   },
>   "proxyControlled": true
> }
> ```

Для начала отключите сторонние расширения в настройках браузера (about:addons), так как управлять прокси может только 1 расширение и при большом их количестве одновременно они могут конфликтовать. После отключения переустановите Censor Tracker, заранее сохранив список проксирования, чтобы его можно было потом сохранить. Произведя переустановку - проверьте работоспособность.

**Comment by PhoenixIndigo** [comment]
Я же писал при добавлении сайт работает. Ваше предложение оно к чему, и не помогает, а несовместимые с другими расширениями удаляю! После переустановки неработает пока не приостановил и не возобнавил работу! Локация Москва, домашний от МГТС с Tele2 с мобилы.
